### ISSUE TITLE
StringIndexOutOfBoundsException with TLS 1.3

### ISSUE THREAD

**Issue by thc202** [spoofzu/DeepViolet#279]
Running a scan against `https://cloudflare.com/` with Java 11, which supports TLS 1.3, leads to:
```
Problem fetching certificate. err=java.lang.StringIndexOutOfBoundsException: begin 4, end -1, length 22
com.mps.deepviolet.api.DVException: java.lang.StringIndexOutOfBoundsException: begin 4, end -1, length 22
	at com.mps.deepviolet.api.DVX509Certificate.<init>(DVX509Certificate.java:116) ~[DeepViolet-5.1.16.jar:na]
	at com.mps.deepviolet.api.DVEng.getCertificate(DVEng.java:214) ~[DeepViolet-5.1.16.jar:na]
	at com.mps.deepviolettools.job.UIBackgroundScanTask.doInBackground(UIBackgroundScanTask.java:532) ~[classes/:na]
	at com.mps.deepviolet.api.DVBackgroundTask.run(DVBackgroundTask.java:107) ~[DeepViolet-5.1.16.jar:na]
Caused by: java.lang.StringIndexOutOfBoundsException: begin 4, end -1, length 22
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[na:na]
	at java.base/java.lang.String.substring(String.java:1874) ~[na:na]
	at com.mps.deepviolet.api.CipherSuiteUtil.getKeyExchangeAlgorithm(CipherSuiteUtil.java:943) ~[DeepViolet-5.1.16.jar:na]
	at com.mps.deepviolet.api.CipherSuiteUtil.checkTrustedCertificate(CipherSuiteUtil.java:872) ~[DeepViolet-5.1.16.jar:na]
	at com.mps.deepviolet.api.DVX509Certificate.assignTrustState(DVX509Certificate.java:344) ~[DeepViolet-5.1.16.jar:na]
	at com.mps.deepviolet.api.DVX509Certificate.onlineInitializationOnly(DVX509Certificate.java:133) ~[DeepViolet-5.1.16.jar:na]
	at com.mps.deepviolet.api.DVX509Certificate.<init>(DVX509Certificate.java:113) ~[DeepViolet-5.1.16.jar:na]
	... 3 common frames omitted
```
In https://github.com/spoofzu/DeepViolet/blob/d0e09b70df96bf016a6f181b927bea6de8ccbb39/src/main/java/com/mps/deepviolet/api/CipherSuiteUtil.java#L935-L947 the `cipher` does not have the `_WITH` part (https://tools.ietf.org/html/rfc8446#appendix-B.4).

Versions:
DeepViolet 5.1.16
java 11 2018-09-25; Java(TM) SE Runtime Environment 18.9 (build 11+28)

Let me know if I need to provide more details. This was the only place that broke with TLS 1.3.

**Comment by spoofzu** [comment]
I have not tried JDK 11 and TLS 1.3 at all.  My requirements note, [JDK 8+ and that TLS 1.3 is not supported](https://github.com/spoofzu/DeepViolet/wiki/Requirements).   That being the case, perhaps I can do some minimal clean-up to get things working for you again.

**Comment by thc202** [comment]
Right, I know that TLS 1.3 is not supported, but since this is just one line change to not break when TLS 1.3 is encountered it seemed worth of fixing sooner.

**Comment by thc202** [comment]
This is no longer happening with version 5.9.
